### Obtener todos los usuarios
GET http://localhost:3000/usuarios

### Obtener usuario por ID
GET http://localhost:3000/usuarios/69444bc4-39f6-11f0-a95b-a8a159de6f1d

### Crear usuario
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nombre": "Luis",
  "apellido_paterno": "Cruzado",
  "apellido_materno": "Gómez",
  "correo": "luis.cruz@exaple.com",
  "numero_telefono": "999808777",
  "dni": "87651321"
}

### Actualizar usuario
PATCH http://localhost:3000/usuarios/7d30ac02-39f6-11f0-a95b-a8a159de6f1d
Content-Type: application/json

{
  "nombre": "Jeremy",
  "apellido_paterno": "Cruzado",
  "apellido_materno": "Gómez",
  "correo": "luis.c@example.com",
  "numero_telefono": "999888777",
  "dni": "87654329"
}

### Eliminar usuario
DELETE http://localhost:3000/usuarios/7d30ac02-39f6-11f0-a95b-a8a159de6f1d