### Obtener todos los usuarios
GET http://localhost:3000/api/usuarios


### Obtener usuario por ID
GET http://localhost:3000/api/usuarios/c216424a-4312-11f0-b45e-a8a159de6f1d

### Crear usuario
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "JEREMY",
  "apellido_paterno": "CruzaDDaGado",
  "apellido_materno": "GómeDDdGsaz",
  "correo": "luis.crGGuz@exapGFahhsdle.com",
  "numero_telefono": "999110787",
  "dni": "87611109"
}

### Actualizar usuario
PATCH http://localhost:3000/api/usuarios/b3b341b2-43fc-11f0-8bc8-a8a159de6f1d
Content-Type: application/json

{
  "nombre": "Jeremy",
  "apellido_paterno": "Cruzadooooooooooo",
  "apellido_materno": "Gómezzzzz",
  "correo": "luis.c@example.com",
  "numero_telefono": "999888777",
  "dni": "87654329"
}

### Eliminar usuario
DELETE http://localhost:3000/api/usuarios/b3b341b2-43fc-11f0-8bc8-a8a159de6f1d






#====== MASCOTAS =====#

### Obtener todas las mascotas
GET http://localhost:3000/api/mascotas

### Obtener mascota por ID
GET http://localhost:3000/api/mascotas/1a1566c6-4550-11f0-bcb0-a8a159de6f1d

### Crear nueva mascota (con id_usuario existente)
POST http://localhost:3000/api/mascotas/
Content-Type: application/json

{
  "nombre": "THOR",
  "raza": "NEGRO",
  "edad": 4,
  "sexo": "M",
  "estado": true,
  "id_usuario": "747c201b-4575-11f0-bcb0-a8a159de6f1d"
}

### Actualizar mascota (cambiar nombre y edad)
PATCH http://localhost:3000/api/mascotas/1a1566c6-4550-11f0-bcb0-a8a159de6f1d
Content-Type: application/json

{
  "nombre": "Maxxxxxxx",
  "raza": "negrooooooooooooo"
}

### Eliminar mascota
DELETE http://localhost:3000/api/mascotas/95a6e8dd-4551-11f0-bcb0-a8a159de6f1d

### 🔄 Cambiar estado de mascota
PATCH http://localhost:3000/api/mascotas/819f0174-4575-11f0-bcb0-a8a159de6f1d
Content-Type: application/json

{
  "estado": true
}



#====== MASCOTAS + USUARIOS =====#


### 🔍 MASCOTAS INNER  USUARIOS
GET http://localhost:3000/api/mascota-usuario






#====== VETERINARIOS =====#
### Obtener todos los veterinarios
GET http://localhost:3000/api/veterinarios


### Obtener veterinario por ID
GET http://localhost:3000/api/veterinarios/e383034c-4a09-11f0-aa02-a8a159de6f1d


### Crear veterinario
POST http://localhost:3000/api/veterinarios
Content-Type: application/json

{
  "nombre": "Andrea",
  "apellido_paterno": "Paredes",
  "apellido_materno": "Velásquez",
  "correo": "andre.pares@example.com",
  "numero_telefono": "987004321",
  "dni": "12300078",
  "estado": true,
  "id_especialidad": 2
}


### Actualizar veterinario
PATCH http://localhost:3000/api/veterinarios/d8973415-4a09-11f0-aa02-a8a159de6f1d
Content-Type: application/json

{
  "numero_telefono": "999999999"
}


### Eliminar veterinario
DELETE http://localhost:3000/api/veterinarios/96a4668b-4a0a-11f0-aa02-a8a159de6f1d


### Cambiar estado del veterinario
PATCH http://localhost:3000/api/veterinarios/7f86ac21-4a0d-11f0-aa02-a8a159de6f1d
Content-Type: application/json

{
  "estado": false
}




#====== SERVICIOS =====#

### Obtener todos los servicios
GET http://localhost:3000/api/servicios

### Obtener servicio por ID
GET http://localhost:3000/api/servicios/bae538ad-4a15-11f0-aa02-a8a159de6f1d

### Crear servicio
POST http://localhost:3000/api/servicios
Content-Type: application/json

{
  "nombre": "Baño y cortee",
  "descripcion": "Servicio completo de higiene",
  "duracion": 30,
  "precio": 45.50,
  "estado": true,
  "id_categoria": 1
}

### Actualizar servicio
PATCH http://localhost:3000/api/servicios/bae538ad-4a15-11f0-aa02-a8a159de6f1d
Content-Type: application/json

{
  "precio": 50.00
}

### Eliminar servicio
DELETE http://localhost:3000/api/servicios/bae538ad-4a15-11f0-aa02-a8a159de6f1d

### Cambiar estado del servicio
PATCH http://localhost:3000/api/servicios/c460ef98-4a15-11f0-aa02-a8a159de6f1d
Content-Type: application/json

{
  "estado": true
}


