### Obtener todos los usuarios
GET http://localhost:3000/api/usuarios

### Obtener usuario por ID
GET http://localhost:3000/api/usuarios/a1b2c3d4-e5f6-7890-1234-56789abcdef0

### Crear usuario
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "Luis",
  "apellido_paterno": "Cruz",
  "apellido_materno": "Gómez",
  "correo": "luis.cruz@example.com",
  "numero_telefono": "999888777",
  "dni": "87654321"
}

### Actualizar usuario
PUT http://localhost:3000/api/usuarios/e15a395f-f773-4c12-b50a-0b087600def3
Content-Type: application/json

{
  "nombre": "Luis",
  "apellido_paterno": "Cruzado",
  "apellido_materno": "Gómez",
  "correo": "luis.c@example.com",
  "numero_telefono": "999888777",
  "dni": "87654329"
}

### Eliminar usuario
DELETE http://localhost:3000/api/usuarios/e15a395f-f773-4c12-b50a-0b087600def3